### PR TITLE
Fix incorrect logic in matrix-parse-url-exit-code

### PR DESCRIPTION
**Pull request by jgkamat**
I was trying to figure out why my stacktraces werent coming up and I finally managed to catch one (which I don't think is related to your PR's):

```
Debugger entered--Lisp error: (wrong-type-argument stringp (401))
  string-match("exited abnormally with code \\([[:digit:]]+\\).*" (401))
  (if (string-match "exited abnormally with code \\([[:digit:]]+\\).*" error-string) (progn (condition-case nil (progn (string-to-int (match-string-no-properties 1 error-string))) (error nil))))
  matrix-parse-curl-exit-code((401))
  (let ((exit-code (matrix-parse-curl-exit-code (cdr (cdr error-thrown))))) (warn (cond ((memq exit-code '(60 51)) "Error sending request to matrix homeserver, SSL certificate is invalid") ((null exit-code) "Unknown error occurred sending request to matrix homeserver: %S") (t (format "Matrix request exited with exit code %d" exit-code)))))
  (progn (let ((--dolist-tail-- matrix-error-hook) handler) (while --dolist-tail-- (setq handler (car --dolist-tail--)) (funcall handler con symbol-status error-thrown) (setq --dolist-tail-- (cdr --dolist-tail--)))) (let ((exit-code (matrix-parse-curl-exit-code (cdr (cdr error-thrown))))) (warn (cond ((memq exit-code '(60 51)) "Error sending request to matrix homeserver, SSL certificate is invalid") ((null exit-code) "Unknown error occurred sending request to matrix homeserver: %S") (t (format "Matrix request exited with exit code %d" exit-code))))))
  (let* ((error-thrown (car (cdr (plist-member args ':error-thrown)))) (symbol-status (car (cdr (plist-member args ':symbol-status))))) (progn (let ((--dolist-tail-- matrix-error-hook) handler) (while --dolist-tail-- (setq handler (car --dolist-tail--)) (funcall handler con symbol-status error-thrown) (setq --dolist-tail-- (cdr --dolist-tail--)))) (let ((exit-code (matrix-parse-curl-exit-code (cdr (cdr error-thrown))))) (warn (cond ((memq exit-code '(60 51)) "Error sending request to matrix homeserver, SSL certificate is invalid") ((null exit-code) "Unknown error occurred sending request to matrix homeserver: %S") (t (format "Matrix request exited with exit code %d" exit-code)))))))
  matrix-request-error-handler(#<matrix-client-connection matrix-client-connection> :data ((errcode . "M_MISSING_TOKEN") (error . "Missing access token.")) :symbol-status error :error-thrown (error http 401) :response #s(request-response :status-code 401 :history nil :data ((errcode . "M_MISSING_TOKEN") (error . "Missing access token.")) :error-thrown (error http 401) :symbol-status error :url "https://matrix.org/_matrix/client/r0/sync?timeout=30000&full_state=true" :done-p nil :settings (:type "GET" :params (("timeout" . "30000") ("full_state" . "true")) :parser json-read :data "null" :error #f(compiled-function (&rest args2) #<bytecode 0x1be7599>) :headers (("Content-Type" . "application/json")) :complete #f(compiled-function (&rest args2) #<bytecode 0x1becf39>) :url "https://matrix.org/_matrix/client/r0/sync?timeout=30000&full_state=true" :response #1) :-buffer #<killed buffer> :-raw-header "HTTP/1.1 401 Unauthorized\nContent-Length: 75\nAccess-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization\nServer: Synapse/0.24.1 (b=matrix-org-hotfixes,7add114)\nDate: Thu, 16 Nov 2017 18:43:22 GMT\nAccess-Control-Allow-Origin: *\nAccess-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS\nContent-Type: application/json\n" :-timer nil :-backend curl :-tempfiles ("/tmp/emacs-requesth7USB4")))
  apply(matrix-request-error-handler (#<matrix-client-connection matrix-client-connection> :data ((errcode . "M_MISSING_TOKEN") (error . "Missing access token.")) :symbol-status error :error-thrown (error http 401) :response #s(request-response :status-code 401 :history nil :data ((errcode . "M_MISSING_TOKEN") (error . "Missing access token.")) :error-thrown (error http 401) :symbol-status error :url "https://matrix.org/_matrix/client/r0/sync?timeout=30000&full_state=true" :done-p nil :settings (:type "GET" :params (("timeout" . "30000") ("full_state" . "true")) :parser json-read :data "null" :error #f(compiled-function (&rest args2) #<bytecode 0x1be7599>) :headers (("Content-Type" . "application/json")) :complete #f(compiled-function (&rest args2) #<bytecode 0x1becf39>) :url "https://matrix.org/_matrix/client/r0/sync?timeout=30000&full_state=true" :response #2) :-buffer #<killed buffer> :-raw-header "HTTP/1.1 401 Unauthorized\nContent-Length: 75\nAccess-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization\nServer: Synapse/0.24.1 (b=matrix-org-hotfixes,7add114)\nDate: Thu, 16 Nov 2017 18:43:22 GMT\nAccess-Control-Allow-Origin: *\nAccess-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS\nContent-Type: application/json\n" :-timer nil :-backend curl :-tempfiles ("/tmp/emacs-requesth7USB4"))))
  #f(compiled-function (&rest args2) #<bytecode 0x1be7599>)(:data ((errcode . "M_MISSING_TOKEN") (error . "Missing access token.")) :symbol-status error :error-thrown (error http 401) :response #s(request-response :status-code 401 :history nil :data ((errcode . "M_MISSING_TOKEN") (error . "Missing access token.")) :error-thrown (error http 401) :symbol-status error :url "https://matrix.org/_matrix/client/r0/sync?timeout=30000&full_state=true" :done-p nil :settings (:type "GET" :params (("timeout" . "30000") ("full_state" . "true")) :parser json-read :data "null" :error #f(compiled-function (&rest args2) #<bytecode 0x1be7599>) :headers (("Content-Type" . "application/json")) :complete #f(compiled-function (&rest args2) #<bytecode 0x1becf39>) :url "https://matrix.org/_matrix/client/r0/sync?timeout=30000&full_state=true" :response #1) :-buffer #<killed buffer> :-raw-header "HTTP/1.1 401 Unauthorized\nContent-Length: 75\nAccess-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization\nServer: Synapse/0.24.1 (b=matrix-org-hotfixes,7add114)\nDate: Thu, 16 Nov 2017 18:43:22 GMT\nAccess-Control-Allow-Origin: *\nAccess-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS\nContent-Type: application/json\n" :-timer nil :-backend curl :-tempfiles ("/tmp/emacs-requesth7USB4")))
  apply(#f(compiled-function (&rest args2) #<bytecode 0x1be7599>) (:data ((errcode . "M_MISSING_TOKEN") (error . "Missing access token.")) :symbol-status error :error-thrown (error http 401) :response #s(request-response :status-code 401 :history nil :data ((errcode . "M_MISSING_TOKEN") (error . "Missing access token.")) :error-thrown (error http 401) :symbol-status error :url "https://matrix.org/_matrix/client/r0/sync?timeout=30000&full_state=true" :done-p nil :settings (:type "GET" :params (("timeout" . "30000") ("full_state" . "true")) :parser json-read :data "null" :error #f(compiled-function (&rest args2) #<bytecode 0x1be7599>) :headers (("Content-Type" . "application/json")) :complete #f(compiled-function (&rest args2) #<bytecode 0x1becf39>) :url "https://matrix.org/_matrix/client/r0/sync?timeout=30000&full_state=true" :response #2) :-buffer #<killed buffer> :-raw-header "HTTP/1.1 401 Unauthorized\nContent-Length: 75\nAccess-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization\nServer: Synapse/0.24.1 (b=matrix-org-hotfixes,7add114)\nDate: Thu, 16 Nov 2017 18:43:22 GMT\nAccess-Control-Allow-Origin: *\nAccess-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS\nContent-Type: application/json\n" :-timer nil :-backend curl :-tempfiles ("/tmp/emacs-requesth7USB4"))))
  apply(apply #f(compiled-function (&rest args2) #<bytecode 0x1be7599>) (:data ((errcode . "M_MISSING_TOKEN") (error . "Missing access token.")) :symbol-status error :error-thrown (error http 401) :response #s(request-response :status-code 401 :history nil :data ((errcode . "M_MISSING_TOKEN") (error . "Missing access token.")) :error-thrown (error http 401) :symbol-status error :url "https://matrix.org/_matrix/client/r0/sync?timeout=30000&full_state=true" :done-p nil :settings (:type "GET" :params (("timeout" . "30000") ("full_state" . "true")) :parser json-read :data "null" :error #f(compiled-function (&rest args2) #<bytecode 0x1be7599>) :headers (("Content-Type" . "application/json")) :complete #f(compiled-function (&rest args2) #<bytecode 0x1becf39>) :url "https://matrix.org/_matrix/client/r0/sync?timeout=30000&full_state=true" :response #2) :-buffer #<killed buffer> :-raw-header "HTTP/1.1 401 Unauthorized\nContent-Length: 75\nAccess-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization\nServer: Synapse/0.24.1 (b=matrix-org-hotfixes,7add114)\nDate: Thu, 16 Nov 2017 18:43:22 GMT\nAccess-Control-Allow-Origin: *\nAccess-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS\nContent-Type: application/json\n" :-timer nil :-backend curl :-tempfiles ("/tmp/emacs-requesth7USB4"))))
  request--safe-apply(#f(compiled-function (&rest args2) #<bytecode 0x1be7599>) (:data ((errcode . "M_MISSING_TOKEN") (error . "Missing access token.")) :symbol-status error :error-thrown (error http 401) :response #s(request-response :status-code 401 :history nil :data ((errcode . "M_MISSING_TOKEN") (error . "Missing access token.")) :error-thrown (error http 401) :symbol-status error :url "https://matrix.org/_matrix/client/r0/sync?timeout=30000&full_state=true" :done-p nil :settings (:type "GET" :params (("timeout" . "30000") ("full_state" . "true")) :parser json-read :data "null" :error #f(compiled-function (&rest args2) #<bytecode 0x1be7599>) :headers (("Content-Type" . "application/json")) :complete #f(compiled-function (&rest args2) #<bytecode 0x1becf39>) :url "https://matrix.org/_matrix/client/r0/sync?timeout=30000&full_state=true" :response #2) :-buffer #<killed buffer> :-raw-header "HTTP/1.1 401 Unauthorized\nContent-Length: 75\nAccess-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization\nServer: Synapse/0.24.1 (b=matrix-org-hotfixes,7add114)\nDate: Thu, 16 Nov 2017 18:43:22 GMT\nAccess-Control-Allow-Origin: *\nAccess-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS\nContent-Type: application/json\n" :-timer nil :-backend curl :-tempfiles ("/tmp/emacs-requesth7USB4"))))
  request--callback(#<killed buffer> :type "GET" :params (("timeout" . "30000") ("full_state" . "true")) :parser json-read :data "null" :error #f(compiled-function (&rest args2) #<bytecode 0x1be7599>) :headers (("Content-Type" . "application/json")) :complete #f(compiled-function (&rest args2) #<bytecode 0x1becf39>) :url "https://matrix.org/_matrix/client/r0/sync?timeout=30000&full_state=true" :response #s(request-response :status-code 401 :history nil :data ((errcode . "M_MISSING_TOKEN") (error . "Missing access token.")) :error-thrown (error http 401) :symbol-status error :url "https://matrix.org/_matrix/client/r0/sync?timeout=30000&full_state=true" :done-p nil :settings (:type "GET" :params (("timeout" . "30000") ("full_state" . "true")) :parser json-read :data "null" :error #f(compiled-function (&rest args2) #<bytecode 0x1be7599>) :headers (("Content-Type" . "application/json")) :complete #f(compiled-function (&rest args2) #<bytecode 0x1becf39>) :url "https://matrix.org/_matrix/client/r0/sync?timeout=30000&full_state=true" :response #1) :-buffer #<killed buffer> :-raw-header "HTTP/1.1 401 Unauthorized\nContent-Length: 75\nAccess-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization\nServer: Synapse/0.24.1 (b=matrix-org-hotfixes,7add114)\nDate: Thu, 16 Nov 2017 18:43:22 GMT\nAccess-Control-Allow-Origin: *\nAccess-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS\nContent-Type: application/json\n" :-timer nil :-backend curl :-tempfiles ("/tmp/emacs-requesth7USB4")))
  apply(request--callback #<killed buffer> (:type "GET" :params (("timeout" . "30000") ("full_state" . "true")) :parser json-read :data "null" :error #f(compiled-function (&rest args2) #<bytecode 0x1be7599>) :headers (("Content-Type" . "application/json")) :complete #f(compiled-function (&rest args2) #<bytecode 0x1becf39>) :url "https://matrix.org/_matrix/client/r0/sync?timeout=30000&full_state=true" :response #s(request-response :status-code 401 :history nil :data ((errcode . "M_MISSING_TOKEN") (error . "Missing access token.")) :error-thrown (error http 401) :symbol-status error :url "https://matrix.org/_matrix/client/r0/sync?timeout=30000&full_state=true" :done-p nil :settings #1 :-buffer #<killed buffer> :-raw-header "HTTP/1.1 401 Unauthorized\nContent-Length: 75\nAccess-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization\nServer: Synapse/0.24.1 (b=matrix-org-hotfixes,7add114)\nDate: Thu, 16 Nov 2017 18:43:22 GMT\nAccess-Control-Allow-Origin: *\nAccess-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS\nContent-Type: application/json\n" :-timer nil :-backend curl :-tempfiles ("/tmp/emacs-requesth7USB4"))))
  request--curl-callback(#<process request curl<1>> "finished\n")
```

Which lead me to the code below.

It seemed to be getting a `'(401)` but wasn't equipped to handle it, this should fix that error.

Another red herring in here is that `string-to-int` isn't a valid function, so I don't think this function ever ran properly.

### CODE REVIEW

**Comment by alphapapa** [comment]
Thanks.  I noticed some issues with this as well.  It seemed to get passed different kinds of args, but I didn't dig into it.  Glad you were able to figure it out.  We probably need more robust error-handling in general, someday.  :)

**Comment by jgkamat** [comment]
Hopefully this improves the state of stacktraces, but we'll have to see. 

What I've been doing is letting it hang for a bit while emacs is tiny (so the backtrace buffer dosen't show up) then running:

```;
(defun jay/debugger-extract ()
    (interactive)
    (with-current-buffer "*Backtrace*"
      (write-file "~/OUTPUT")))
```

Kind of a hack, but at least I can get stacktraces now :smile: 

The wrapping didn't help too much, I think we have to limit the stacktrace depth if we want in-emacs backtraces...

**Comment by alphapapa** [comment]
That is a clever hack.  So the backtrace is created but the window isn't shown since the frame is too small, and then you can call that function because the process itself isn't hung?

**Comment by jgkamat** [comment]
Yup! In practice, I've needed to wait a bit, then `C-g` a couple times (but the backtrace is still stored), so I can dump it out.

**Comment by alphapapa** [comment]
Great!  I think you should write a blog post about this, or at least a post on /r/emacs, because I think this technique would help a lot of people!  

That is, assuming everyone suffers from the 100%-CPU-on-wrapping-backtraces issue.  I haven't seen any mention of it before, which was making me wonder if I was the only one.  I wonder if there's a deeper issue, because I can't imagine all the Emacs devs suffering from this problem and not fixing it...

**Comment by jgkamat** [comment]
I'm fairly confident this is because our backtraces are huge mine was 9mb on 50 lines or so, with most being on one line. 

Even stock vim froze when I tried to scroll down, so I suppose this is to be expected. I _still_haven't found a way to limit the traceback depth, but I'll keep looking (and if I do, I might write about it :D)

**Pull request merged**
