### PR TITLE
Add: Last-seen line

### PR DESCRIPTION
**Pull request by alphapapa**
Wasn't too hard, and is really handy.

### CODE REVIEW

**Comment by alphapapa** [comment]
Cool.  :)  Maybe you can help me figure out something, though: Emacs doesn't have a very good way to hook when a frame is focused in the window system (i.e. X--I don't know about other GUIs), so we can't move the last-seen line when the user focuses/activates the Emacs window.  The only way I can find is to use the focus-in/out hooks, but that means maintaining our own state for the whole Emacs process or frame, which seems like something we'd want to avoid.

So the result is, to get the last-seen line to move, the user has to either a) select a different window in the frame, or b) send a message.  It would be nice to fix this at some point.

**Comment by jgkamat** [comment]
I searched around for a way to do this for my [erc plugin](https://github.com/jgkamat/erc-scrolltoplace), which needs to hook when people view a buffer. I ended up using [this package](https://github.com/10sr/switch-buffer-functions-el), which hooks post-command-hook to sort of get this. It's a hack, but it mostly works....

**Comment by alphapapa** [comment]
Cool, I'll check it out.  Thanks.

**Comment by jgkamat** [comment]
FWIW, I think this is great even as is, so I'm fine with merging this and adding a hook for buffer switching later, but your choice!

**Pull request closed without merging**
